### ISSUE TITLE
Mac 无法读取证书

### ISSUE THREAD

**Issue by Akamight** [monkeyWie/proxyee-down#124]
在按照作者提供的标准流程安装Proxyee-Down v2.21和SwitchyOmega后，在启动Proxyee-Down的时候系统报错：无法启动jar文件，日志如下
默认	19:03:06.620347 +0800	launchservicesd	CHECKIN:0x0-0x60060 2118 com.apple.JarLauncher
默认	19:03:16.635633 +0800	Jar Launcher	LSExceptions shared instance invalidated for timeout.
而Main文件夹里面的core可以正常启动，但是启动时报错并且计入了日志文件：
2018-02-08  19:05:53.680 [JavaFX Application Thread] ERROR lee.study.down.gui.HttpDownApplication - install cert error:
java.io.IOException: Cannot run program "certutil": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at lee.study.down.util.WindowsUtil.existsCert(WindowsUtil.java:120)
	at lee.study.down.gui.HttpDownApplication.beforeOpen(HttpDownApplication.java:102)
	at lee.study.down.gui.HttpDownApplication.start(HttpDownApplication.java:160)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 14 common frames omitted
而控制台输出：
默认	19:05:48.451839 +0800	launchservicesd	CHECKIN:0x0-0x63063 2127 com.apple.JarLauncher
默认	19:05:58.465195 +0800	Jar Launcher	LSExceptions shared instance invalidated for timeout.
经过测试，程序无法调用SwitchyOmega来获取下载地址，从而影响了正常的程序功能.
Java: JDK 1.9 + JDK 1.8 都试过了
macOS版本: macOS High Sierra

**Comment by monkeyWie** [comment]
这个错误没影响的
