### ISSUE TITLE
树莓派中无法运行

### ISSUE THREAD

**Issue by jiubao** [monkeyWie/proxyee-down#148]
### 问题描述(必要)
树莓派中无法运行
### 版本号(必要)
proxyee-down-2.22-jar.zip
### 操作系统(必要)
树莓派 RASPBIAN STRETCH WITH DESKTOP Kernel version:4.9
### 相关截图
![image](https://user-images.githubusercontent.com/8424102/36342114-59c4f726-1434-11e8-93d3-0f055192d0c8.png)
### 相关日志
没有日志

**Comment by monkeyWie** [comment]
运行main目录的proxyee-down-core.jar试试

**Comment by ruoleng** [comment]
sudo java -jar proxyee-down-core.jar

Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 16 more

运行2.44的 proxyee-down-core.jar 后报这个

**Comment by monkeyWie** [comment]
需要安装javafx，最好是直接下载oracle jre运行

**Comment by ruoleng** [comment]
直接安装了JDK的。 树莓派是ARM的 32位 Linux。
可能是Java版本太老。
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

安装指引上的下载地址也没有ARM的JRE可以下载。

**Comment by monkeyWie** [comment]
下载linux的jre就行，可以参考下最新的linux安装教程
https://github.com/monkeyWie/proxyee-down/blob/master/.guide/linux/read.md

**Comment by ruoleng** [comment]
查了资料，Oracle 已经放弃了对树莓派的支持了。最新的JDK，JRE都没有JavaFX了。
卸载了Oracle-JDK8 。

用 
sudo apt-get install OpenJFX
 安装完成后，用：
sudo java -jar proxyee-down.jar
能跑起来。
也看到任务栏的 proxyee-down 的图标了。但是打开127.0.0.1:9999 找不到页面。没办法安装证书。
在任务栏图标上面右键，证书根目录也找不到。

跑了一会后，好像卡死了。估计树莓派CPU太弱吧
