### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by updater1234** [monkeyWie/proxyee-down#151]
### 相关日志[bryan@bryan-pc main]$ java -jar proxyee-down-core.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

**Comment by note286** [comment]
@updater1234 `java -jar proxyee-down.jar` 是启动这个jar包吧

**Comment by monkeyWie** [comment]
jre什么版本啊

**Comment by updater1234** [comment]
jre9

**Comment by monkeyWie** [comment]
用jre8试试

**Comment by jy97799** [comment]
我猜你需要
`sudo apt install jfx`

**Comment by LamGC** [comment]
可能是直接启动了核心包导致的问题吧
core不用管，不用运行

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by houbaron** [comment]
@jy97799 You got it! 装上这个包，瞬间启动。
