### ISSUE TITLE
合并下载解压失败

### ISSUE THREAD

**Issue by md5xwl** [monkeyWie/proxyee-down#164]
### 问题描述(必要)
合并下载视频，解压出来的都是坏的，无法播放。打包一次下5集，可能能解压出来3集，但是都不能播放。一集一集下好像没啥问题。
### 相关日志
好几段差不多这样的log。

2018-03-01  14:38:07.957 [nioEventLoopGroup-2-1] ERROR lee.study.down.handle.HttpDownInitializer - down onChunkError:
java.io.IOException: Ô¶³ÌÖ÷»úÇ¿ÆÈ¹Ø±ÕÁËÒ»¸öÏÖÓÐµÄÁ¬½Ó¡£
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Comment by md5xwl** [comment]
下载的资源 ，    链接: https://pan.baidu.com/s/1eTn841c 密码: ace3

**Comment by monkeyWie** [comment]
视频大概有多大

**Comment by monkeyWie** [comment]
你用什么工具解压的？

**Comment by md5xwl** [comment]
自动解压和手动用rar解压都不行。现在放弃在虚拟机里面用了。弄了台台式机可以正常使用。
