### ISSUE TITLE
ubuntu编译成功，但无法启动

### ISSUE THREAD

**Issue by zhezh** [monkeyWie/proxyee-down#21]
ubuntu 16.04 x64，前面编译均正常通过。
jdk 9.0.1
node 9.3.0
Apache Maven 3.3.9

Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.10.0-33-generic", arch: "amd64", family: "unix"

target 目录
.
├── main
│   └── proxyee-down-core.jar
└── proxyee-down.jar
两个jar文件，均给了可执行权限

报错：
```
proxyee-down/target$ java -jar proxyee-down.jar 

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at lee.study.down.util.OsUtil.<clinit>(OsUtil.java:15)
	at lee.study.down.util.PathUtil.<clinit>(PathUtil.java:34)
	at lee.study.down.Bootstrap.<clinit>(Bootstrap.java:20)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

```

**Comment by monkeyWie** [comment]
@zhezh
更新下./update/pom.xml文件，然后重新用mvn编译下

**Comment by monkeyWie** [comment]
@zhezh 
用git更新下文件内容就行了，然后再按前面的maven命令编译

**Comment by zhezh** [comment]
@monkeyWie 感谢回复！我以为maven有什么骚操作可以自动更新pom的。。就忘了查看下项目的更新情况了。

我删了原来的代码，从git重新clone了，并且删掉了home下的`~/.m2/repository/lee`，从第一步重新开始。

编译完后，用系统自带的java和手动下载的jdk尝试启动，报同样的错误，如下：
```
~/softwares/jdk/jdk-9.0.1/bin$ ./java -jar ~/softwares/proxyee-baidu/proxyee-down/target/proxyee-down.jar 
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at lee.study.down.Bootstrap.<clinit>(Bootstrap.java:29)
```

java版本：
```
java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
和
```
~/softwares/jdk/jdk-9.0.1/bin$ ./java -version 
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

```
echo $JAVA_HOME
# /home/name/softwares/jdk/jdk-9.0.1
```

不知道是不是我电脑的问题

**Comment by monkeyWie** [comment]
贴一下你的lee.study.down.Bootstrap.java代码

**Comment by zhezh** [comment]
`~/softwares/proxyee-baidu/proxyee-down/update/src/main/java/lee/study/down/Bootstrap.java`



```
package lee.study.down;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import lee.study.down.util.PathUtil;

public class Bootstrap {

  public static void main(String[] args) throws Exception {
    Runtime.getRuntime().addShutdownHook(new Thread(() -> {
      if (process != null) {
        process.destroy();
      }
    }));
    fork();
  }

  private static final String MAIN_PATH = PathUtil.ROOT_PATH + "main" + File.separator;
  private static final String CORE_PATH = MAIN_PATH + "proxyee-down-core.jar";
  private static final String UPDATE_PATH = MAIN_PATH + "proxyee-down-core.jar.bak";
  private static Process process;
  private static String JAVA_EXEC_HOME;

  static {
    String execPath = File.separator + "bin" + File.separator + "java.exe";
    File dir = new File(PathUtil.ROOT_PATH);
    File[] files = dir.listFiles((d, name) -> d.isDirectory() && name.indexOf("jre") > -1);
    if (files.length > 0) {
      JAVA_EXEC_HOME = files[0].getAbsolutePath()+execPath;
    } else {
      JAVA_EXEC_HOME = System.getenv("JAVA_HOME") + execPath;
    }
    JAVA_EXEC_HOME = "\"" + JAVA_EXEC_HOME + "\"";
  }

  private static void fork() throws Exception {
    process = Runtime.getRuntime().exec(JAVA_EXEC_HOME + " -jar \"" + CORE_PATH + "\"");
    BufferedReader br = new BufferedReader(new InputStreamReader(process.getInputStream()));
    String line;
    boolean isUpdate = false;
    while ((line = br.readLine()) != null) {
      System.out.println(line);
      if ("proxyee-down-update".equals(line)) {
        isUpdate = true;
        break;
      }
    }
    if (isUpdate) {
      process.destroy();
      replaceJar();
      fork();
    }
  }

  private static void replaceJar() throws InterruptedException {
    File updateFile = new File(UPDATE_PATH);
    File beforeFile = new File(CORE_PATH);
    if (updateFile.exists()) {
      if (beforeFile.exists()) {
        if (!delete(beforeFile)) {
          System.exit(1);
        }
      }
      updateFile.renameTo(new File(CORE_PATH));
    }
  }

  private static boolean delete(File file) throws InterruptedException {
    for (int i = 0; i < 30; i++) {
      if (file.delete()) {
        return true;
      }
      Thread.sleep(1000);
    }
    return false;
  }
}
```

**Comment by monkeyWie** [comment]
改成这个再mvn package下运行看看输出什么
```
System.out.println("rootPath:"+PathUtil.ROOT_PATH);
File[] files = dir.listFiles((d, name) -> d.isDirectory() && name.indexOf("jre") > -1);
System.out.println("files:"+files);
    if (files.length > 0) {
      JAVA_EXEC_HOME = files[0].getAbsolutePath()+execPath;
    } else {
      JAVA_EXEC_HOME = System.getenv("JAVA_HOME") + execPath;
    }
```

**Comment by zhezh** [comment]
我把原文件 28-33行改为了上面的代码

```
static {
    String execPath = File.separator + "bin" + File.separator + "java.exe";
    File dir = new File(PathUtil.ROOT_PATH);
    System.out.println("rootPath:"+PathUtil.ROOT_PATH);
    File[] files = dir.listFiles((d, name) -> d.isDirectory() && name.indexOf("jre") > -1);
    System.out.println("files:"+files);
        if (files.length > 0) {
          JAVA_EXEC_HOME = files[0].getAbsolutePath()+execPath;
        } else {
          JAVA_EXEC_HOME = System.getenv("JAVA_HOME") + execPath;
        }
    JAVA_EXEC_HOME = "\"" + JAVA_EXEC_HOME + "\"";
  }
```

mvn clean package后，执行jar
```
java -jar target/proxyee-down.jar 
rootPath:<username.>/softwares/proxyee-baidu/proxyee-down/target/
files:null
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at lee.study.down.Bootstrap.<clinit>(Bootstrap.java:31)

```

**Comment by zhezh** [comment]
`rootPath:home/username/softwares/proxyee-baidu/proxyee-down/target/`
难道是home 前面少个`/`?

**Comment by monkeyWie** [comment]
@zhezh 
应该是linux上的bug，你可以看看lee.study.down.util.PathUtil，然后修改下，在运行看看
···
 URL url = PathUtil.class.getResource("/");
    String path = url != null ? url.getPath() : PathUtil.class.getResource("").getPath();
    System.out.println("path :"+path);
···
```
 System.out.println("ROOT_PATH :"+ROOT_PATH );
if (OsUtil.isWindows() && ROOT_PATH.indexOf("/") == 0) {
      ROOT_PATH = ROOT_PATH.substring(1);
    }
```

**Comment by zhezh** [comment]
加了这两处print后，输出为：
```
java -jar target/proxyee-down.jar 
path :file:/home/username/softwares/proxyee-baidu/proxyee-down/target/proxyee-down.jar!/lee/study/down/util/
ROOT_PATH :home/username/softwares/proxyee-baidu/proxyee-down/target/
rootPath:home/username/softwares/proxyee-baidu/proxyee-down/target/
files:null
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at lee.study.down.Bootstrap.<clinit>(Bootstrap.java:31)

```

**Comment by monkeyWie** [comment]
谢谢你的反馈，正则修改成以下代码应该就行了
```
Pattern pattern = Pattern.compile("^file:(/[^!]*/)[^/]+\\.jar!/.*$");
```

**Comment by zhezh** [comment]
看起来跨平台的坑还有很多，
改完正则后，报错。

```
java -jar target/proxyee-down.jar 
path :file:/home/username/softwares/proxyee-baidu/proxyee-down/target/proxyee-down.jar!/lee/study/down/util/
ROOT_PATH :/home/username/softwares/proxyee-baidu/proxyee-down/target/
rootPath:/home/username/softwares/proxyee-baidu/proxyee-down/target/
files:[Ljava.io.File;@58372a00
Exception in thread "main" java.io.IOException: Cannot run program ""/home/username/softwares/jdk/jdk-9.0.1/bin/java.exe"": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at lee.study.down.Bootstrap.fork(Bootstrap.java:40)
	at lee.study.down.Bootstrap.main(Bootstrap.java:16)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more

```
我把`java`可执行文件通过link和复制两种方式创建`java.exe`均不行，也许是因为路径有两个双引号。

**Comment by zhezh** [comment]
Bootstrap.java改动如下，可以不报错，不过不知道是否成功运行，因为并没有界面什么的。
等两天再继续折腾

```
static {
    String execPath = File.separator + "bin" + File.separator + "java";
    File dir = new File(PathUtil.ROOT_PATH);
    System.out.println("rootPath:"+PathUtil.ROOT_PATH);
    File[] files = dir.listFiles((d, name) -> d.isDirectory() && name.indexOf("jre") > -1);
    System.out.println("files:"+files);
        if (files.length > 0) {
          JAVA_EXEC_HOME = files[0].getAbsolutePath()+execPath;
        } else {
          JAVA_EXEC_HOME = System.getenv("JAVA_HOME") + execPath;
        }

    System.out.println("JAVA_EXEC_HOME:"+JAVA_EXEC_HOME);
  }
```

**Comment by monkeyWie** [comment]
嗯 估计是这个双引号的问题，修改下lee.study.down.Bootstrap.java
```
private static final String MAIN_PATH = PathUtil.ROOT_PATH + "main" + File.separator;
  private static final String CORE_PATH = MAIN_PATH + "proxyee-down-core.jar";
  private static final String UPDATE_PATH = MAIN_PATH + "proxyee-down-core.jar.bak";
  private static Process process;
  private static String CMD;

  static {
    String execPath = File.separator + "bin" + File.separator + "java.exe";
    File dir = new File(PathUtil.ROOT_PATH);
    File[] files = dir.listFiles((d, name) -> d.isDirectory() && name.indexOf("jre") > -1);
    String javaHome;
    if (files != null && files.length > 0) {
      javaHome = files[0].getAbsolutePath() + execPath;
    } else {
      javaHome = System.getenv("JAVA_HOME") + execPath;
    }
    if (OsUtil.isWindows()) {
      CMD = "\"" + javaHome + "\" -jar \"" + CORE_PATH + "\"";
    } else {
      CMD = javaHome + " -jar " + CORE_PATH;
    }
  }

  private static void fork() throws Exception {
    process = Runtime.getRuntime().exec(CMD);
    BufferedReader br = new BufferedReader(new InputStreamReader(process.getInputStream()));
    String line;
    boolean isUpdate = false;
    while ((line = br.readLine()) != null) {
      System.out.println(line);
      if ("proxyee-down-update".equals(line)) {
        isUpdate = true;
        break;
      }
    }
    if (isUpdate) {
      process.destroy();
      replaceJar();
      fork();
    }
  }
```

**Comment by zhezh** [comment]
fixed
