### ISSUE TITLE
双击最小化之后无法再次显示

### ISSUE THREAD

**Issue by zz234807** [monkeyWie/proxyee-down#216]
### 相关截图
2018-03-27  16:47:10.611 [Thread-19] ERROR lee.study.down.task.PluginUpdateCheckTask - plugin update error
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:730)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:706)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:299)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:288)
	at lee.study.down.task.PluginUpdateCheckTask.run(PluginUpdateCheckTask.java:25)

**Comment by zz234807** [comment]
具体操作就是双击顶部窗口顶部会缩小窗口。之后就再也打不开了。删除整个文件夹重新下载一次再start可以打开

**Comment by monkeyWie** [comment]
是个bug，临时解决方案退出软件然后把main目录里的.recods.inf文件删除

**Comment by baloyou** [comment]
@monkeyWie 刚刚测试下载了一个百度云文件，确实突破限速了，厉害。

不过，我也碰到了这样的问题：下载中，隐藏窗口后就弹不出来了，不管是点软件的“显示”，还是右键dock上的“显示所有窗口”，不过从网络上看，下载还在继续，下完之后我强行关闭一下试试。

**Comment by 14SHIKE** [comment]
2.42版本应该能解决这个  窗口最小化后不能打开  的问题

**Comment by monkeyWie** [comment]
2.42已修复
