### ISSUE TITLE
下载中断

### ISSUE THREAD

**Issue by w-jin** [monkeyWie/proxyee-down#260]
问题：下载中断，卡在14%了，昨晚卡在12%了，文件总共6.08G；
操作系统为win10 x64 1709；
软件版本为2.44；
日志过长，我截取典型片断：
2018-04-10  10:45:36.552 [nioEventLoopGroup-2-1] ERROR lee.study.down.handle.HttpDownInitializer - down onChunkError:
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
此段连续出现，时间相近；

2018-04-10  11:00:49.281 [nioEventLoopGroup-2-1] WARN  lee.study.down.handle.HttpDownInitializer - 响应状态码异常：302	ChunkInfo(index=29, oriStartPosition=5913241984, nowStartPosition=5941237244, 
随后出现此段，也是连续出现，直到末尾。

**Comment by monkeyWie** [comment]
尝试刷新链接https://github.com/monkeyWie/proxyee-down/blob/master/.guide/common/refresh/read.md
