### ISSUE TITLE
mac   编译没报错.但是 报这个 "null/bin/java.exe"

### ISSUE THREAD

**Issue by Daopr** [monkeyWie/proxyee-down#31]
⋊> ~/c/p/target on master ◦ java -jar proxyee-down.jar                  09:04:08
Exception in thread "main" java.io.IOException: Cannot run program "null/bin/java.exe": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at lee.study.down.Bootstrap.fork(Bootstrap.java:44)
	at lee.study.down.Bootstrap.main(Bootstrap.java:17)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)

**Comment by Daopr** [comment]
切换到 dev 后运行了,但
Started HttpDownApplication in 3.782 seconds (JVM running for 4.738)
写入配置文件失败：
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at lee.study.down.util.FileUtil.createFile(FileUtil.java:68)
	at lee.study.down.util.ByteUtil.serialize(ByteUtil.java:97)
	at lee.study.down.util.ByteUtil.serialize(ByteUtil.java:108)
	at lee.study.down.content.ConfigContent.save(ConfigContent.java:33)
	at lee.study.down.content.ConfigContent.init(ConfigContent.java:52)
	at lee.study.down.content.ContentManager.init(ContentManager.java:10)
	at lee.study.down.HttpDownApplication.main(HttpDownApplication.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
HttpDownProxyServer listen 9999	proxyConfig:null

**Comment by monkeyWie** [comment]
能输出下java.io.IOException: No such file or directory这里，写入的文件路径是什么吗

**Comment by monkeyWie** [comment]
@Daopr 
版本更新了，你可以update下再试试

**Comment by Daopr** [comment]
好的,我晚上试试

**Comment by p0we7** [comment]
@monkeyWie macOS 10.12.6 已经把 JRE JDK都装了 ，出现如下错误

```
➜  proxyee-down-2.11-jar java -jar proxyee-down.jar 
Exception in thread "main" java.io.IOException: Cannot run program "null/bin/java": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:635)
	at java.base/java.lang.Runtime.exec(Runtime.java:459)
	at java.base/java.lang.Runtime.exec(Runtime.java:356)
	at lee.study.down.Bootstrap.fork(Bootstrap.java:44)
	at lee.study.down.Bootstrap.main(Bootstrap.java:17)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:339)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:270)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 6 more
➜  proxyee-down-2.11-jar which java                
/usr/bin/java
```

**Comment by monkeyWie** [comment]
@p0we7  这行命令有问题吧
```
proxyee-down-2.11-jar java -jar proxyee-down.jar
```

**Comment by p0we7** [comment]
@monkeyWie proxyee-down-2.11-jar 是文件夹名称来的 .

空格之后的 java 开始才是输入的命令

**Comment by p0we7** [comment]
[![asciicast](https://asciinema.org/a/6Upw9rSXVQhBGFBPR8EjgLb3N.png)](https://asciinema.org/a/6Upw9rSXVQhBGFBPR8EjgLb3N)

**Comment by monkeyWie** [comment]
@p0we7 
是自己编译的还是下载的relese版的呢

**Comment by p0we7** [comment]
@monkeyWie  release 上面的 2.11版本

**Comment by monkeyWie** [comment]
把全路径提供下，你再换个没有特殊符号的路径试试看

**Comment by p0we7** [comment]
@monkeyWie 

```
➜  proxyee-down-2.11-jar pwd                                        
/Users/power/Downloads/proxyee-down-2.11-jar

```

没有特殊字符的.

**Comment by monkeyWie** [comment]
有JAVA_HOME环境变量吗

**Comment by p0we7** [comment]
@monkeyWie  第一次在 macOS 用java, 谢谢拉

**Comment by LW0NG** [comment]
Exception in thread "main" java.io.IOException: Cannot run program "/**/**/**/proxyee/jre1.8.0_162/Contents/Home/bin/java": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at lee.study.down.Bootstrap.fork(Bootstrap.java:38)
	at lee.study.down.Bootstrap.main(Bootstrap.java:17)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
