### ISSUE TITLE
中文字体为乱码方框。

### ISSUE THREAD

**Issue by fanyuanqi** [monkeyWie/proxyee-down#322]
### 相关截图
http://t.bebove.com/data/admin/Screenshot_20180428_19490420180428194940.png
### 相关日志

2018-04-28  19:37:22.268 [JavaFX Application Thread] ERROR lee.study.down.content.ConfigContent - ¼ÓÔØÅäÖÃÎÄ¼þÊ§°Ü£º
java.lang.NullPointerException: null
        at lee.study.down.content.ConfigContent.set(ConfigContent.java:27)
        at lee.study.down.content.ConfigContent.init(ConfigContent.java:51)
        at lee.study.down.content.ContentManager.init(ContentManager.java:10)
        at lee.study.down.gui.HttpDownApplication.initHandle(HttpDownApplication.java:111)
        at lee.study.down.gui.HttpDownApplication.start(HttpDownApplication.java:198)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:748)

**Comment by jerryzyz008** [comment]
还有18.04下没有托盘显示啊，即使装了topicons plus也不行
