### ISSUE TITLE
下载文件夹到97%就没速度了

### ISSUE THREAD

**Issue by Magnetic2014** [monkeyWie/proxyee-down#335]
### 问题描述(必要)
下载两个文件夹做测试，下载其中一个文件夹时只能到97%，之后就没有速度了。另外一个正常。
刷新下载链接和删除任务重新下载都没有用。
分段数试过32和64，也都是97%就停止了。
### 版本号(必要)
2.52
### 操作系统(必要)
Ubuntu 16.04 LTS，下载目录有读写权限
### 相关截图
![image](https://user-images.githubusercontent.com/14221971/39560075-940f8756-4ecd-11e8-97ec-15e43058329f.png)
![image](https://user-images.githubusercontent.com/14221971/39560091-aac5d96e-4ecd-11e8-9465-cabcf1d7baed.png)
### 相关日志
我就选其中一段吧，其他的都跟这个一样是connection reset，前后一共有十几次：
```
2018-05-03  12:02:39.700 [nioEventLoopGroup-2-1] ERROR lee.study.down.handle.HttpDownInitializer - down onChunkError:
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by monkeyWie** [comment]
你可以试试单文件下载，或者不包含文件夹的批量下载
