### ISSUE TITLE
mac下java无响应

### ISSUE THREAD

**Issue by kiok1210** [monkeyWie/proxyee-down#385]
### 问题描述(必要)
在下载一个任务的时候，再去嗅探一个任务，会死掉，不完全测试，在嗅探大于1G文件的时候会出现这个情况。
看了下日志，貌似是并发问题。难道只能单任务下载吗？但是也不是，已经嗅探的任务可以多个同时下载。
还有，能提个意见吗？是不是可以加个重新下载的功能，因为确实有时候有这样的需求。
### 版本号(必要)
2.54
### 操作系统(必要)
mac 10.12.6
### 相关截图
截图不截取了
### 相关日志2018-05-19  08:48:35.653 [nioEventLoopGroup-6-1] ERROR lee.study.down.handle.HttpDownInitializer - down onChunkError:
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Comment by monkeyWie** [comment]
不会啊，死掉是什么情况？
