### ISSUE TITLE
解压BUG

### ISSUE THREAD

**Issue by Silence21** [monkeyWie/proxyee-down#84]
解压过程中显示服务器异常，版本2.11,异常信息：
2018-02-01  18:07:52.276 [http-nio-9000-exec-10] ERROR lee.study.down.mvc.exception.RestExceptionHandler - rest error:
java.io.FileNotFoundException: F:\ITvideo (拒绝访问。)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at lee.study.down.io.BdyZip.unzip(BdyZip.java:121)
	at lee.study.down.mvc.controller.HttpDownController.bdyUnzip(HttpDownController.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by monkeyWie** [comment]
换一个目录试试
